services:
  haretropanel:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    environment:
      TZ: Europe/Berlin
      HARETROPANEL_PORT: "8080"
      HARETROPANEL_LOG_FILE: "/app/logs/haretropanel.log"
      HARETROPANEL_LOG_LEVEL: "haretropanel=info,tower_http=info"

    ports:
      - "8080:8080"

    volumes:
      - ./logs:/app
      - ./data:/app/data

    restart: unless-stopped

    network_mode: host